matrix:
  include:
    - language: node_js
      node_js:
        - 9
      dist: trusty
      sudo: false

      branches:
        only:
          - master

      cache:
        directories:
          - node_modules

      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable

      before_install:
        - cd Client/

      install:
        - npm install

      script:
        - npm run build --prod

    - language: csharp
      mono: none
      dotnet: 2.2
      dist: xenial
      sudo: required

      branches:
        only:
          - master

      before_install:
        - cd Server/

      install:
        - dotnet restore

      script:
        - dotnet build

      global:
        - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
        - DOTNET_CLI_TELEMETRY_OPTOUT=1

notifications:
  email: false
